I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 51, in script call
    call dayOneCard from _call_dayOneCard
  File "game/script.rpy", line 51, in script call
    call dayOneCard from _call_dayOneCard
ScriptError: could not find label 'dayOneCard'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 51, in script call
    call dayOneCard from _call_dayOneCard
  File "C:\Users\Nick\Documents\renpy-6.99.13-sdk\renpy\ast.py", line 1336, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 51, in script call
    call dayOneCard from _call_dayOneCard
  File "C:\Users\Nick\Documents\renpy-6.99.13-sdk\renpy\script.py", line 861, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'dayOneCard'.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
A Sun Of Salt 1.0
