I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 57, in script call
    call day3 from _call_day3
  File "renpy/common/00start.rpy", line 120, in script
    return
Exception: Could not find return label (u'C:\\Users\\Nick\\Documents\\renpy-6.99.13-sdk\\ASunOfSalt/game/day3.rpy', 1530850087, 138).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 57, in script call
    call day3 from _call_day3
  File "renpy/common/00start.rpy", line 120, in script
    return
  File "C:\Users\Nick\Documents\renpy-6.99.13-sdk\renpy\ast.py", line 1400, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Nick\Documents\renpy-6.99.13-sdk\renpy\execution.py", line 586, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'C:\\Users\\Nick\\Documents\\renpy-6.99.13-sdk\\ASunOfSalt/game/day3.rpy', 1530850087, 138).

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
A Sun Of Salt 1.0
